unit RtspConstants;
{$mode objfpc}{$H+}
interface
const
RTSP_METHOD_OPTIONS = 'OPTIONS';
RTSP_METHOD_DESCRIBE = 'DESCRIBE';
RTSP_METHOD_SETUP = 'SETUP';
RTSP_METHOD_PLAY = 'PLAY';
RTSP_METHOD_PAUSE = 'PAUSE';
RTSP_METHOD_TEARDOWN = 'TEARDOWN';
RTSP_200_OK = 200;
RTSP_400_BAD_REQUEST = 400;
RTSP_404_NOT_FOUND = 404;
RTSP_454_SESSION_NOT_FOUND = 454;
RTSP_500_INTERNAL_ERROR = 500;
RTSP_501_NOT_IMPLEMENTED = 501;
RTSP_HDR_CSEQ = 'CSeq'; RTSP_HDR_SESSION = 'Session';
RTSP_HDR_TRANSPORT = 'Transport'; RTSP_HDR_PUBLIC = 'Public';
RTSP_VERSION = 'RTSP/1.0';
RTSP_SERVER_NAME = 'RTSPServer/1.0 (Pascal)';
RTSP_ALL_METHODS = 'OPTIONS, DESCRIBE, SETUP, PLAY, PAUSE, TEARDOWN';
CRLF = #13#10;
implementation
end.
